
import java.awt.Color;
import javax.swing.JOptionPane;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdel
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login_page
     */
    public login_page() {
        initComponents();
        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user_n = new javax.swing.JTextField();
        user_p = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        showp = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(0, 118, 221));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 38, -1));

        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 118, 221));
        jButton2.setText("login");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jLabel1.setText("incorrect username or password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));

        user_n.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_n.setForeground(new java.awt.Color(0, 118, 221));
        user_n.setText("Enter username");
        user_n.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_nFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_nFocusLost(evt);
            }
        });
        getContentPane().add(user_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 310, -1));

        user_p.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_p.setForeground(new java.awt.Color(0, 118, 221));
        user_p.setText("enter password");
        user_p.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_pFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_pFocusLost(evt);
            }
        });
        getContentPane().add(user_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 310, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 118, 221));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        jButton3.setText("login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, -1, -1));

        showp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showp.setForeground(new java.awt.Color(0, 118, 221));
        showp.setText("Show password");
        showp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpActionPerformed(evt);
            }
        });
        getContentPane().add(showp, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login background.PNG"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1300, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_nFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_nFocusGained
       jLabel1.setVisible(false);
       if (user_n.getText().equals("Enter username")){
           user_n.setText("");
           user_n.setForeground(new Color(0,118,221) );
                    
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nFocusGained

    private void user_nFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_nFocusLost
       
        jLabel1.setVisible(false);
       if (user_n.getText().equals("")){
           user_n.setText("Enter username");
                  user_n.setForeground(new Color(0,118,221) );      
       }

// TODO add your handling code here:
    }//GEN-LAST:event_user_nFocusLost
//
    private void user_pFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_pFocusGained
       
    jLabel1.setVisible(false);
       if (user_p.getText().equals("enter password")){
           user_p.setText("");
           user_p.setForeground(new Color(0,118,221) );    

       }
// TODO add your handling code here:
    }//GEN-LAST:event_user_pFocusGained

    private void user_pFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_pFocusLost
       
 jLabel1.setVisible(false);
       if (user_p.getText().equals("")){
           user_p.setText("enter password");
                  user_p.setForeground(new Color(0,118,221) );      
       }        
// TODO add your handling code here:
    }//GEN-LAST:event_user_pFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        int a=JOptionPane.showConfirmDialog(null ,"Do you realy want to exit application","Select",JOptionPane.YES_NO_OPTION );
          
        if (a ==0){
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        if (user_n.getText().equals("gms1")&&user_p.getText().equals("admin"))
        {
            setVisible(false);
            new Home().setVisible(true);
           
        }else
        {
       jLabel1.setVisible(true);
        
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void showpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpActionPerformed
            if(showp.isSelected()){
                user_p.setEchoChar('\0');
            
            }else
            {
                user_p.setEchoChar('#');
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_showpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox showp;
    private javax.swing.JTextField user_n;
    private javax.swing.JPasswordField user_p;
    // End of variables declaration//GEN-END:variables
}
